Set-MsolUserPassword -UserPrincipalName	301ivanov.as@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	302ivanov.i@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	302ivanova.aa@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	304jakovenko.i@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	305jakupova.a@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	306janush.o@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	307jaremenko.i@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	308jaroshenko.a@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	309kaira.i@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	310a.v@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	311inichenko.oo@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	312ljan.o@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	313kalyta.d@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	314kamashev.a@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
Set-MsolUserPassword -UserPrincipalName	315kamrat.v@novaposhta.ua	-NewPassword "P@ssw0rd" -ForceChangePassword $false
